/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../components/about/About.vue')['default']
    AboutPanel: typeof import('./../components/more/AboutPanel.vue')['default']
    DonateDrawer: typeof import('./../components/DonateDrawer.vue')['default']
    EmoticonItem: typeof import('./../components/emoticon/EmoticonItem.vue')['default']
    EmoticonList: typeof import('./../components/emoticon/EmoticonList.vue')['default']
    EmoticonViewer: typeof import('./../components/emoticon/EmoticonViewer.vue')['default']
    Home: typeof import('./../components/Home.vue')['default']
    ImageCarousel: typeof import('./../components/ImageCarousel.vue')['default']
    ImageItem: typeof import('./../components/ImageItem.vue')['default']
    ImageList: typeof import('./../components/ImageList.vue')['default']
    ImageSourceSwitcher: typeof import('./../components/ImageSourceSwitcher.vue')['default']
    ImageStarList: typeof import('./../components/ImageStarList.vue')['default']
    MoreDrawer: typeof import('./../components/MoreDrawer.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    Settings: typeof import('./../components/setting/Settings.vue')['default']
    SettingsPanel: typeof import('./../components/more/SettingsPanel.vue')['default']
    SourceHealthCheck: typeof import('./../components/SourceHealthCheck.vue')['default']
    SourceSwitcher: typeof import('./../components/source/SourceSwitcher.vue')['default']
    StarDrawer: typeof import('./../components/star/StarDrawer.vue')['default']
  }
}
